[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/generated/prisma/libquery_engine-*"]
  external_node_modules = ["@prisma/client", "prisma"]

# Handle redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 