[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/generated/prisma/**"]
  external_node_modules = ["@prisma/client"]

[dev]
  command = "npm run frontend"
  port = 3000
  targetPort = 5173
  framework = "#custom"
  publish = "dist"

# Handle redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 