[build]
  command = "remix build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "remix dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild" 