[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Prisma generates during build
[build.environment]
  PRISMA_GENERATE_DURING_BUILD = "true"

# Copy Prisma engine files
[[plugins]]
  package = "netlify-plugin-prisma-fix"

# Handle redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 